rss_feeds:
- url: https://en-forum.guildwars2.com/discover/6.xml
  webhooks:
  - https://discord.com/api/webhooks/0123456789/kjsdkfjhsdlfgkjhsddklhjsdfbsdkfjbsdkfjbaslm
  last_item_date: Fri, 10 Nov 2023 17:01:53 +0000
twitter_feeds:
- include_retweets: true
  url: https://nitter.woodland.cafe/that_shaman/rss
  webhooks:
  - https://discord.com/api/webhooks/0123456789/kjsdkfjhsdlfgkjhsddklhjsdfbsdkfjbsdkfjbaslm
  - https://discord.com/api/webhooks/0123456789/kjsdkfjhsdlfgkjhsddklhjsdfbsdkfjbsdkfjbaslm
  last_item_date: Thu, 09 Nov 2023 16:25:33 GMT
error_webhook: - https://discord.com/api/webhooks/0123456789/kjsdkfjhsdlfgkjhsddklhjsdfbsdkfjbsdkfjbaslm
